### ISSUE TITLE
Använd två olika fonter

### ISSUE THREAD

**Issue by NinjaGrandpa** [NinjaGrandpa/Webbutveckling-Labb1#1]
# Fonts

1. ## Headers
- ### [League Gothic](https://fonts.google.com/specimen/League+Gothic?preview.text=LONGWATER%20RECORDS&preview.text_type=custom&query=gothic)
- ### [Eczar](https://fonts.google.com/specimen/Eczar)

2. ## Body Text
- ### [Gentium Plus](https://fonts.google.com/specimen/Gentium+Plus?query=gentium)

## Imports
```html
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Eczar&family=Gentium+Plus&display=swap" rel="stylesheet">
```

```css
.headers {
   font-family: 'Eczar', serif;
}

p {
   font-family: 'Gentium Plus', serif;
}
```

## Tasks
- [x] Change fonts in Index
   - [x] Import in HTML
   - [x] Headers
   - [x] Body Text
- [x] Change fonts in About
   - [x] Import in HTML
   - [x] Headers
   - [x] Body Text
- [x] Change fonts in Shop
   - [x] Import in HTML
   - [x] Headers
   - [x] Body Text
